### ISSUE TITLE
Exception in thread "main" java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by wsnoble** [wenbostar/pepmap#2]
Can you help me understand this error? What file is missing?

Also, I find it concerning that it says it's finding 2 proteins in sample.fasta, which contains just a single protein.

```
% java -jar pepmap-2.0.0.jar -i peptides.txt -d sample.fasta -i2l -o matched
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[print_parameters:484] - Mapping parameter:
pepmap version: 2.0.0
Database: sample.fasta
Input peptide file for mapping: peptides.txt
Don't distinguish I and L: true
The number of mismatch: 0
The max ratio of X in a match: 0.0
The min length of peptide: 0
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:67] - Don't distinguish I and L during peptide mapping.
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:80] - Start indexing fasta file

2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:92] - Indexing took 0.118685042 seconds and consumes 6.0E-4 MB
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:102] - Total number of valid unique peptides in input file 'peptides.txt': 8
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:103] - Total number of invalid unique peptides in input file 'peptides.txt': 0
2023-09-27 14:42:29 [INFO ] main.java.PeptideMapper[run:104] - Total number of proteins in database 'sample.fasta': 2
Exception in thread "main" java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2063)
	at main.java.PeptideMapper.generate_peptide_files(PeptideMapper.java:544)
	at main.java.PeptideMapper.run(PeptideMapper.java:116)
	at main.java.PepMap.main(PepMap.java:63)
```
[peptides.txt](https://github.com/wenbostar/pepmap/files/12743527/peptides.txt)
[sample.fasta.txt](https://github.com/wenbostar/pepmap/files/12743528/sample.fasta.txt)

**Comment by wenbostar** [comment]
A quick fix to this is to create the folder of "matched" before run the command line.
