### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by wsnoble** [wenbostar/pepmap#6]
What am I doing wrong here?

```
java -jar /Users/wnoble/proj/2023_wnoble_denovo-fdr/bin/pepmap-2.0.0.jar -i no_match_50.txt -i2l -d 0602_Universal_Contaminants.fasta
2024-03-19 12:33:37 [INFO ] main.java.PeptideMapper[print_parameters:511] - Mapping parameter:
pepmap version: 2.0.0
Database: 0602_Universal_Contaminants.fasta
Input peptide file for mapping: no_match_50.txt
Don't distinguish I and L: true
The number of mismatch: 0
The max ratio of X in a match: 0.0
The min length of peptide: 0
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at main.java.PeptideMapper.run(PeptideMapper.java:51)
	at main.java.PepMap.main(PepMap.java:63)
```
[no_match_50.txt](https://github.com/wenbostar/pepmap/files/14654922/no_match_50.txt)

The input file is attached. The FASTA is [here](https://github.com/HaoGroup-ProtContLib/Protein-Contaminant-Libraries-for-DDA-and-DIA-Proteomics/blob/main/Universal%20protein%20contaminant%20FASTA/0602_Universal%20Contaminants.fasta)

**Comment by wenbostar** [comment]
It will work if you add "-o ./".

**Comment by wsnoble** [comment]
Thanks.  You might want to add checks for required command line arguments.
